version: '3'
services:
  db:
   image: postgres:9.6
   ports:
     - "5432:5432"
   volumes:
     - /home/james/dev/py/worlds_collide/pg_data:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=${PG_USER}
     - POSTGRES_PASSWORD=${PG_PASS}
     - POSTGRES_DB=worlds_collide
  django:
    build: ./django/
    command: python worldscollide/manage.py runserver 0.0.0.0:3001
    volumes:
      - ./django/:/usr/src/app
    ports:
      - "3001:3001"
    environment:
     - PG_USER=${PG_USER}
     - PG_PASS=${PG_PASS}
     - PG_HOST=${PG_HOST}
     - DJANGO_SECRET=${DJANGO_SECRET}
    depends_on:
     - db
  pyramid:
    build: ./pyramid/
    command: python -u main.py
    volumes:
      - ./pyramid/:/usr/src/app
    ports:
      - "3002:6543"
    environment:
     - PG_USER=${PG_USER}
     - PG_PASS=${PG_PASS}
     - PG_HOST=${PG_HOST}
    depends_on:
     - db
  flask:
    build: ./flask/
    command: python -u worldscollide.py
    volumes:
      - ./flask/:/usr/src/app
    ports:
      - "3003:5000"
    environment:
     - PG_USER=${PG_USER}
     - PG_PASS=${PG_PASS}
     - PG_HOST=${PG_HOST}
     - FLASK_SECRET=${FLASK_SECRET}
    depends_on:
     - db
  tornado:
    build: ./tornado/
    command: python -u main.py
    volumes:
      - ./tornado/:/usr/src/app
    ports:
      - "3004:3004"
    environment:
     - PG_USER=${PG_USER}
     - PG_PASS=${PG_PASS}
     - PG_HOST=${PG_HOST}
     - TORNADO_PORT=3004
    depends_on:
     - db
  front:
    image: jmfirth/webpack
    command: webpack-dev-server --hot --inline --progress --host 0.0.0.0
    ports:
     - "3000:8080"
    volumes:
     - ./front/:/app
    depends_on:
     - pyramid
